"""add source_id to deposits and subscriptions

Revision ID: a1a38c84507b
Revises: 0001
Create Date: 2026-05-10 10:38:59.089421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1a38c84507b'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('source_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_deposits_source_id'), 'deposits', ['source_id'], unique=False)
    op.add_column('subscriptions', sa.Column('source_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_subscriptions_source_id'), 'subscriptions', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_subscriptions_source_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'source_id')
    op.drop_index(op.f('ix_deposits_source_id'), table_name='deposits')
    op.drop_column('deposits', 'source_id')
